const fs = require('fs')
const path = require('path')
const requestBody = fs.readFileSync(path.join(__dirname, './target.html'))
const parserHTML = require('./html-parse')
const dom = parserHTML(requestBody.toString())
// console.log(JSON.stringify(dom, ' ', 2))
fs.writeFileSync(path.join(__dirname, './output.json'), JSON.stringify(dom, ' ', 2))
console.log('parser over')